motivation=[
    'I am worthy of a wealthy life.',
    'Productivity is being able to do things that you were never able to do before',
    'Money comes to me in miraculous ways',
    'I am deserving of abundance in my life.',
    'I am open to receive wealth in many ways.',
    'I love my positive, happy, abundant life.',
    'Strive not to be a success, but rather to be of value.',
    'Sometimes, things may not go your way, but the effort should be there every single night.',
    'Until we can manage time, we can manage nothing else.',
    'If you look for the negative, it will be there. If you look for the positive, it will OVERWHELM you.',
    'Dissect how you spend your time. It reveals your priorities.',
    'The more I give, the more I receive. The more I receive, the more I give.',
    'Make it your daily obsession to make the most of your potential.',
    'I only attract healthy, loving relationships.',
    'You can get better at whatever you want to do.',
    'Failure is temporary. Move quickly past it. What lies beyond the failure is the lesson.',
    'Whatever you focus on you will become.',
    'I am compassionate with others and myself.',
    'I attract positive people into my life.',
    'I am becoming a better version of myself one day at a time.',
    'I happily give and receive love each day.',
    'I am worthy of having what I want.',
    'The more I let go, the better I feel.',
    'I am stronger than I seem.',
    'I am braver than I think.',
    'I have unshakable faith.',
    'Miracles are taking place in my life.',
    'My relationship will be open, honest and full of abundance.',
    'My partner is a reflection of me.',
    'I exhale negativity and inhale happiness.'
    'I feel profound empathy and love for others and their own unique paths.',
    'I choose to stop apologizing for being me.',
    'I am at peace with all that has happened in my life.',
    'Happiness flows from me',
    'I am grounded, peaceful, and centered.',
    'I am blessed!',
    'I do not judge myself or others.',
    'I overflow with creativity and good ideas.',
    'I am breathing effortlessly with lungs that are pure and clean.',
    'I am confidently checking the balance of my bank account as I make adeposit of $1,000,000.',
    'I feel at ease as I speak in public',
    "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.",
    "Begin - to begin is half the work, let half still remain; again begin this, and thou wilt have finished",
    "Nothing has such power to broaden the mind as the ability to investigate systematically and truly all that comes under thy observation in life.",
    "Time is a sort of river of passing events, and strong is its current; no sooner is a thing brought to sight than it is swept by and another takes its place, and this too will be swept away.",
    "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
    "Nowhere can man find a quieter or more untroubled retreat than in his own soul.",
    "Everything that happens happens as it should, and if you observe carefully, you will find this to be so.",
    "If it is not right do not do it; if it is not true do not say it. ",
    "Here is the rule to remember in the future, When anything tempts you to be bitter: not, 'This is a misfortune' but 'To bear this worthily is good fortune.",
    "We ought to do good to others as simply as a horse runs, or a bee makes honey, or a vine bears grapes season after season without thinking of the grapes it has borne.",
    "A noble man compares and estimates himself by an idea which is higher than himself; and a mean man, by one lower than himself. The one produces aspiration; the other ambition, which is the way in which a vulgar man aspires.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Because a thing seems difficult for you, do not think it impossible for anyone to accomplish.",
    "Such as are your habitual thoughts, such also will be the character of your mind; for the soul is dyed by the thoughts.",
    "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.",
    "Anything in any way beautiful derives its beauty from itself and asks nothing beyond itself. Praise is no part of it, for nothing is made worse or better by praise.",
    "Do every act of your life as if it were your last.",
    "Death is a release from the impressions of the senses, and from desires that make us their puppets, and from the vagaries of the mind, and from the hard service of the flesh.",
    "Our life is what our thoughts make it.",
    "Loss is nothing else but change, and change is Nature's delight.",
    "How much time he saves who does not look to see what his neighbor says or does or thinks.",
    "Forward, as occasion offers. Never look round to see whether any shall note it... Be satisfied with success in even the smallest matter, and think that even such a result is no trifle.",
    "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.",
    "Life is neither good or evil, but only a place for good and evil.",
    "He who lives in harmony with himself lives in harmony with the universe.",
    "The only wealth which you will keep forever is the wealth you have given away.",
    "I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinions of himself than on the opinions of others."
]