tradingquotes=["The goal of a successful trader is to make the best trades. Money is secondary.",
        "Do more of what works and less of what doesn’t.",
        "Never, ever argue with your trading system",
        "In this business, if you’re good, you’re right six times out of ten. You’re never going to be right nine times out of ten",
        "After a bottom or top is made or at the beginning of any calendar year, you should go back over 3,5,7 and 10-year periods to see if the market is repeating and which one of these periods it is running closest to.",
        "As a trader, you have to decide what is more important—being right or making money—because the two are not always compatible or consistent with one another."
        "The hard, cold reality of trading is that every trade has an uncertain outcome.",
        "If you never really know where the market may stop, it is very easy to believe there are no limits to how much you can make on any given trade. This characteristic will allow you to indulge yourself in the illusion that each trade has the potential of fulfilling your wildest dream of financial independence. If you fall in this trap then you will have the tendency to gather only the kind of market information that will confirm and reinforce your belief, all the while denying vital information that may be telling you the best opportunity is in the opposite direction.",
        "Release yourself from the notion that each trade has the potential to fulfill all your dreams. ",
        "If you are in a profitable trade, is there ever enough? Greed stems from a belief that there is never enough or there won't be enough. If you are in a losing trade, you won't want it to exist because it represents failure, so you can just act as if it doesn't, by convincing yourself that you are in a winning trade that hasn't gone in your favor yet.",
        "Only trade with money you can afford to lose.",
        "The less meaning the money has, the less potential there is for your personal -how much is enough- issues to contaminate your perception of market movement.",
        "To become a consistently successful trader your objective has to be to learn how to let the market tell you what it may do next and how much is enough.",
        "Trading blunders, such as refusing to recognize losses, or failing to reverse positions when the market turns, are rooted in psychological and emotional blindness.",
        "Thinking of the market as being right or wrong is a mistake. The market is – that’s all.",
        "Traders should liberate themselves from notions and beliefs that prevent them from considering all available information objectively and dispassionately.",
        "Take direction from the market, not from your hopes, greed or fear.",
        "Self-control, emotional restraint and flexibility are not part of the market. They are part of you, but they are not innate; you have to learn them",
        "The few individuals who have achieved astronomical success in trading at some point learned to stop trying to conquer the markets, or make them conform to their expectations or mental limitations.",
        "Focus on improving your skills instead of on the money you have at stake. ",
        "Determine how much risk you can comfortably bear, and how to bear more prudently.",
        "Control your beliefs about the market.",
        "Distinguish your true intuitions from false hunches",
        "No matter what a trader thinks, believes, expects or knows – the market is always right. ",
        "A careful observer can infer where the market is likely to go next. However, clinging to your inferences if the market moves in another direction is a mistake. ",
        "Remain objective; see the market as it is, not as you hope it will be.",
        "Entering the market is easier than exiting it. Getting out of a trade means curbing greed, if the trade is winning, or recognizing losses, if the trade is going down.",
        "Most traders do not see the market clearly. They are either so eager to win back what the market has taken, or to see a modest gain turn into an amazing win, that they see the market through a dark fog of their own making.",
        "The market is like a stream, but one that can reverse its flow. You may enter at any point and it can move in any direction",
        "Because the market does not provide structure or limits, you must provide your own. You write your own rules and you must take responsibility for your decisions – and their consequences. ",
        "Most traders do not want to take this responsibility. If they establish rules, then they have a standard to use to measure their performance. This means they have to face the fact that bad decisions are their own fault. They are unwilling to plan because plans also imply accountability. Yet they want to make money. They are impatient. So they follow the crowd, moving back and forth, implicitly turning responsibility for their decisions over to others.  ",
        "When you develop self-control, self-discipline and accountability, and when you take responsibility for writing rules, making plans and holding yourself accountable, you separate yourself from the crowd. Then you can observe it from the outside. You can begin to understand and predict the crowd’s behavior precisely because you are not part of it. ",
        "Because the market consists of traders making individual decisions that they themselves do not clearly understand, no one really understands why the market does what it does.",
        "Locals (who trade only for their own accounts) are the most short-term, impatient, impulsive, active traders. They tend to move together.",
        "The more positive you feel about yourself, the more abundance...will naturally flow your way as a by-product of these positive feelings.",
        "Much of what we experience of the outside environment is shaped from the inside.",
        "You are responsible for your perceptions of the market. You define it as an opportunity or a threat, depending on what you believe and understand. You assign the meaning to market moves. The market merely does what it does.",
        "Negative emotions carry energy that blurs your vision and weakens your execution.",
        "Your fear is not really a fear of the market, but a lack of self-confidence. What you fear is acting decisively.",
        "Fear can be paralyzing. Similarly, your ability to let profits grow depends on your valuation of yourself. You reward yourself by giving yourself money, but only to the extent that your self-valuation tells you that you deserve it.",
        "If you believe that you do not deserve the money, you will not accumulate gains. Your ability to accept yourself as you really are determines your ability to change, grow, develop new skills and achieve new goals.",
        "What you believe, what you remember and how you associate things with each other to shape your world are part of the continuous loop operating between your external and internal environment.",
        "People tend to be attached to the correctness of their beliefs and are reluctant to admit that their beliefs could be wrong.",
        "For example, suppose a trader fears losses, but sees an opportunity to profit. He enters the market, but it moves against him. Instead of accepting the fact that he was wrong about the opportunity, taking a small loss and getting out, the trader turns his attention to information that lets him go on believing that he was right. His fear of loss leads him into greater and greater losses. The same sort of trader, given a winning trade, is apt to exit prematurely, cutting profits short. Why? His fear of loss leads him to think only of the likelihood that the market will turn against him, and to disregard the fact that it is going his way.",
        "Trade systematically.",
        "Develop expertise in one market pattern and trade within conditions you fully understand, disregarding others.",
        ]

knowledgefrombooks = [
        "The master trader is inclined to compare trading activity in the first hour versus the last hour of trading. The more sophisticated traders tend to trade in the last hour of a session (when the market is down) while the irrational investors trade more in the first hour of trading (when the market is up).  That’s a sign that there is a distribution going on by smarter investors.",
        "When the market is down in the morning and up in the afternoon, that means the smarter investors are accumulating."
        "Digging deeper for material about a company helps you know what to trade bigger and where to add when it is going against you. Having a good story can produce a real impact",
        "Each of your movements should be explainable and have a significance that can be factored into making future trading assessments.",
        "The trader’s challenge is to time the information in the context of other things that he knows about the stock and its trading pattern. He has to keep assessing a wide variety of data to find which information is significant at a particular period of time. Information may not be pertinent six months from now.",
        "if you act on the material too early, it can hurt you. If you have it too late, it can’t help you. The key is timing the trade based on your analysis of the data, recognizing that the value of the analysis decays over time and may be factored into the price of a stock.",
        "Ideally you want to begin trading just before the information influences the analysts to make their recommendation. To do this you want to be aware of catalysts such as earnings reports, conferences, and analysts meetings, where critical information may influence the price of stocks.",
        "The Labor Department’s employment report is released on the first Friday of every month and is based on data from the previ- ous month. It is an indicator of employment and wage growth and provides four pieces of data: nonfarm payrolls (jobs), the unemployment rate, the average hourly wages, and the average workweek.",
        "The productivity report is released by the Department of Labor on a quarterly basis. It measures output per worker hour and worker compensation costs per unit of output produced.",
        "Have sense of company's Income Statement, Cash Flow, Balance Sheet, Estimates",
        "smart trader wants to under- stand the business model, whether the business is scaleable, how to leverage the business model in order to understand whether a com- pany is going to be profitable, and why one company will achieve greater profits and higher multiples than another.",
        "list of important questions to consider: What are the critical factors that make a stock attractive in this group?, Are there seasonal trends in the stock’s performance?, Are there key number releases that can influence short-term price action in the stocks?, Which of your buys have a chance of working this month? Which are second-halfers?, What is the history of the booms and busts in their group over the past few years?",
        "Buy signals: Improved earnings that are about to be announced in addition to the fact that the chart patterns may be looking positive. Good inventory controls, limiting markdown risk, and improving gross margins. Comp store sales above internal projections. Reduced expenses.",
        "In addition, most companies in most sectors are likely to benefit from news that they are joining with a strategic partner or signing a re- seller agreement to help sell their supply. They also usually benefit from news that a major brokerage house is projecting several years of solid growth or is initiating coverage of a stock for the first time. ",
        "The daily chart is where I do most of my analysis, but I select my opportunities based upon the trend of the weekly charts.",
        "I have to be humble to reverse. I have to be willing to admit that the market knows more about where it is going than do I. I can't force a market to do my bidding. have to be flexible and yield to its greater power.",
        "trading range is that prices are in congestion lor at least 21 to 29 days.",
        "A swing looks like this /\, or this \/. The legs of a swing look like \, or /, but are usually not of equal length.What I'm looking for here is a reaction that constitutes either a .382 or .618 retracement of the latest leg of a swing. At or between these two points there will almost certainly be some sort of resistance.",
        "Two bars against you and a gap down on day 3 and youre not out of there? how many times must you make stupod mistakes like that before you learn?",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        "a",
        
        ]
