waveabcimages = [
    "AB = CD - bearish XA",
    "AB=CD - Bullish XA",
    "AB=CD - summary",
    "ABC & WXY - Zig zag & double zig zag",
    "Flat - expanded",
    "Flat - Fib multiples",
    "Flat - Regular and expanding",
    "Flat - Regular, Expanding and Running",
    "Flat - running",
    "Flat - running2",
    "Flat 0",
    "Flat 1",
    "Flat 2",
    "Market corrective",
    "Triangle - ABCDE",
    "Triangle - Contracting",
    "Triangle - Expanding1",
    "Triangles 1",
    "Triangles 2",
    "Triangles Contracting and Expanding",
    "Triangle ascending examples",
    "Triangles - Descending examples",
    "Wave C - Find pattern first",
    "Wave C - Market impulse2",
    "Wave C - Pattern 1",
    "Wave C - Pattern 2",
    "Wave C - Pattern 3",
    "Wave C - Pattern 4 & 5",
    "Wave C failure",
    "Wave C has 5 waves",
    "Wave C waves",
    "Wedge - Ascending example",
    "WXY - Double 3",
    "WXY - triple 3",
    "Zig Zag 0",
    "Zig zag 1",
    "Zigzag - double",
    "Zigzag - Tripple ",
    "Zigzag 2",
]

tradingotherimages=[
    "8 Revesal Patterns",
    "Breakout chart patterns",
    "Bullish, bearish, reversal patterns",
    "Bungee",
    "Bungee and semaphore details",
    "Candlestick formations",
    "Cup with handle examples",
    "Diamonds - examples",
    "DTosc",
    "DTosc rules",
    "Flags examples",
    "Support Failure example",
    "W.D.Gann rules",
    "Gann fann",
    "Gaps",
    "Rounded Tops examples",
    "Wavy tunnel Breakout 1",  
    "Wavy tunnel Breakout 2",
    "Wavy tunnel Breakout 3",
    "Wavy tunnel Breakout 3 & 4",
    "Wavy tunnel Breakout 4",
    "Wavy tunnel setup",
    "Wyckoff - Accumilation",
    "Wyckoff - Accumulation schematic 1",
    "Wyckoff - conceptual map",
    "Wyckoff - Distribution",
    "Wyckoff - Schematics of Accumulation",
    "Wyckoff - Schematics of Distribution",
    "Wyckoff Logic1",
]

retracements = [
    "AB = CD - Fib retracements",
    "Extensions retracements",
    "Fib convergance 1",
    "Fib convergance 2",
    "Fib convergance 3",
    "Triangles fib multiples",
    "w1-2, w3-4 abc retracement",
    "Wave extension fibbanoci",
    "Zig zag - retracements of Wave C and Y",
    "Zig zag - Wave B retracement",
]

allwavesimages = [
    "Correct and incorrect counting",
    "Correct and incorrect counting 2",
    "Diagonal",
    "Elliott Wave with its inner waves",
    "Ending Diagonal",
    "Ending Diagonal 2",
    "Extensions",
    "Impulse",
    "Impulse wave fib",
    "Leading Diagonal 1",
    "Leading Diagonal 2",
    "Market impulse using wave C",
    "Wave 1 - info",
    "Wave 1 or Wave A?",
    "Wave 2 - info",
    "Wave 2 consists of",
    "Wave 3 - info",
    "Wave 3 has 5 smaller waves",
    "Wave 4 - info",
    "Wave 4 & 2 has 3 smaller waves",
    "Wave 5 ends..",
    "Wave 5 triangle - info",
    "Waves targets"
    
]